### ISSUE TITLE
NullPointerException with Burp v2.0.17 and 1.7.37

### ISSUE THREAD

**Issue by felmoltor** [ikkisoft/blazer#11]
Hello,

Installed blazer extension(v0.3 - 01 Feb 2017) for Burp v2.017 but whenever I try to use it from the proxy history, the extension returns the following error. I tryed to use the tree options provided, AMF Testing, AMF2XML and Enable/Disable Sec manager:

`java.lang.NullPointerException
	at burp.CustomMenuItem.menuItemClicked(BurpExtender.java:153)
	at burp.cta.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

Is this a known issue?

Thank you.

EDIT: Tested with 1.7.37 Pro and a similar error pop-ups in the extension output:

`java.lang.NullPointerException
	at burp.CustomMenuItem.menuItemClicked(BurpExtender.java:153)
	at burp.he.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by ikkisoft** [comment]
This extension is no longer supported, and it works on Burp 1.7.x only. You can download the 1.7 version from Portswigger website.
